#!/bin/sh
set -eu

if [ "$#" -ne 1 ]; then
    exit 64
fi

case "$1" in
    suspend)
        exec /usr/bin/systemctl suspend
        ;;
    reboot)
        exec /usr/bin/systemctl reboot
        ;;
    poweroff)
        exec /usr/bin/systemctl poweroff
        ;;
    *)
        exit 64
        ;;
esac
