#!/bin/sh
set -eu

lb config noauto \
    --mode debian \
    --distribution trixie \
    --architecture amd64 \
    --archive-areas "main contrib non-free non-free-firmware" \
    --binary-image iso-hybrid \
    --bootloaders "grub-efi,syslinux" \
    --debian-installer none \
    --linux-packages none \
    --apt-recommends true \
    --firmware-binary true \
    --firmware-chroot true \
    --uefi-secure-boot disable \
    --iso-application "Cartheon OS" \
    --iso-publisher "Cartheon OS Project" \
    --iso-volume "CARTHEON" \
    --image-name "cartheon-os" \
    --bootappend-live "boot=live components quiet splash username=player hostname=cartheon locales=en_US.UTF-8 keyboard-layouts=us"
